ALTER TABLE compositions ADD COLUMN IF NOT EXISTS bpm INTEGER DEFAULT 120;
ALTER TABLE compositions ADD COLUMN IF NOT EXISTS time_signature VARCHAR(8) DEFAULT '4/4';

ALTER TABLE shared_songs ADD COLUMN IF NOT EXISTS bpm INTEGER DEFAULT 120;
ALTER TABLE shared_songs ADD COLUMN IF NOT EXISTS time_signature VARCHAR(8) DEFAULT '4/4';
